"""Core modules for MOL-JAX PDE solver."""

from moljax.core.grid import Grid1D, Grid2D
from moljax.core.state import (
    StateDict,
    tree_add,
    tree_sub,
    tree_scale,
    tree_axpy,
    tree_norm2,
    tree_norm_inf,
    tree_vdot,
    flatten_to_vec,
)
from moljax.core.bc import BCType, FieldBCSpec, apply_bc
from moljax.core.operators import (
    d1_central_1d,
    d1_upwind_1d,
    d2_central_1d,
    laplacian_1d,
    d1_central_2d,
    d1_upwind_2d,
    d2_central_2d,
    laplacian_2d,
    LinearOp,
    NonlinearOp,
    fd_laplacian_symbol_1d,
    fd_laplacian_symbol_2d,
)
from moljax.core.model import MOLModel
from moljax.core.stepping import (
    IntegratorType,
    euler_step,
    ssprk3_step,
    rk4_step,
    be_step,
    cn_step,
    bdf2_step,
    adaptive_integrate,
    imex_euler_step,
    imex_strang_step,
    imex_ssprk2_step,
    adaptive_integrate_imex,
    integrate_imex_fixed_dt,
)
from moljax.core.newton_krylov import newton_krylov_solve
from moljax.core.preconditioners import (
    IdentityPreconditioner,
    BlockJacobiPreconditioner,
    DiffusionPreconditioner,
    FFTDiffusionPreconditioner,
    FFTAdvectionDiffusionPreconditioner,
    create_fft_preconditioner,
    create_gray_scott_fft_preconditioner,
    create_advdiff_fft_preconditioner,
)
from moljax.core.dt_policy import (
    propose_dt,
    CFLParams,
    PIDParams,
    imex_cfl_dt,
    propose_dt_imex,
)
from moljax.core.fft_solvers import (
    create_fft_cache,
    create_fft_cache_1d,
    create_fft_cache_2d,
    FFTCache1D,
    FFTCache2D,
    laplacian_symbol_1d,
    laplacian_symbol_2d,
    solve_helmholtz,
    solve_helmholtz_1d,
    solve_helmholtz_2d,
    apply_diffusion_inverse_fft,
    apply_diffusion_fft,
    apply_spectral_filter_state,
    exponential_filter_1d,
    exponential_filter_2d,
)
from moljax.core.fft_operators import (
    FFTLinearOperator,
    DiffusionOperator,
    AdvectionDiffusionOperator,
    exact_cfl_dt,
)
from moljax.core.fft_integrators import (
    etd1_step,
    etd2_step,
    etdrk4_step,
    etd_integrate,
    diffusion_only_etd1,
    imex_euler_step as fft_imex_euler_step,
    batched_fft_matvec,
    batched_fft_solve,
    batched_fft_exp_matvec,
    stacked_fft_solve_shared_op,
)
from moljax.core.jit_kernels import (
    phi1,
    phi2,
    phi3,
    etd1_kernel_1d,
    etd1_kernel_2d,
    etd2_kernel_1d,
    etdrk4_kernel_1d,
    helmholtz_solve_1d,
    helmholtz_solve_2d,
    advdiff_solve_1d,
    batched_fft_solve_1d,
    batched_exp_matvec_1d,
    make_etd1_integrator,
    benchmark_jit_speedup,
    # Batched multi-field operations
    batched_etd1_kernel_1d,
    batched_etd2_kernel_1d,
    multi_operator_etd1_1d,
    batched_etd1_kernel_2d,
    batched_helmholtz_solve_2d,
    benchmark_batched_scaling,
    print_batched_scaling_report,
)
from moljax.core.gpu_benchmarks import (
    DeviceInfo,
    BenchmarkResult,
    ScalingBenchmark,
    benchmark_fft_scaling,
    benchmark_2d_scaling,
    run_full_benchmark,
    print_benchmark_report,
)
from moljax.core.fft_nonperiodic import (
    BCType as NonperiodicBCType,
    NonperiodicFFTCache,
    laplacian_symbol_dirichlet,
    laplacian_symbol_neumann,
    laplacian_symbol_mixed_dn,
    create_nonperiodic_fft_cache,
    solve_poisson_dirichlet,
    solve_poisson_neumann,
    solve_helmholtz_dirichlet,
    solve_helmholtz_neumann,
    etd1_dirichlet,
    etd1_neumann,
    dst_I_fast,
    idst_I_fast,
)
from moljax.core.operators_ho import (
    # 4th-order 1D operators
    d1_fourth_order_1d,
    d2_fourth_order_1d,
    d1_ho_1d,
    d2_ho_1d,
    laplacian_ho_1d,
    # 4th-order 2D operators
    d1_ho_2d,
    d2_ho_2d,
    laplacian_ho_2d,
    # FFT symbols for higher-order stencils
    fd_laplacian_symbol_ho_1d,
    fd_laplacian_symbol_ho_2d,
    fd_d1_symbol_ho_1d,
    # 6th-order
    d2_sixth_order_1d,
    fd_laplacian_symbol_6th_1d,
    # Symbol selectors
    get_laplacian_symbol_1d,
    get_laplacian_symbol_2d,
    OperatorOrder,
)
from moljax.core.variable_coeff import (
    VariableCoeffStats,
    CirculantApprox,
    compute_coeff_stats,
    create_circulant_approx_1d,
    create_circulant_approx_2d,
    apply_variable_diffusion_1d,
    apply_variable_diffusion_2d,
    solve_helmholtz_circulant_1d,
    solve_helmholtz_circulant_2d,
    richardson_iteration_varcoeff_1d,
    richardson_iteration_varcoeff_2d,
    assess_circulant_quality,
    etd1_varcoeff_approx_1d,
    print_varcoeff_report,
)

__all__ = [
    # Grid
    "Grid1D",
    "Grid2D",
    # State
    "StateDict",
    "tree_add",
    "tree_sub",
    "tree_scale",
    "tree_axpy",
    "tree_norm2",
    "tree_norm_inf",
    "tree_vdot",
    "flatten_to_vec",
    # Boundary conditions
    "BCType",
    "FieldBCSpec",
    "apply_bc",
    # Operators
    "d1_central_1d",
    "d1_upwind_1d",
    "d2_central_1d",
    "laplacian_1d",
    "d1_central_2d",
    "d1_upwind_2d",
    "d2_central_2d",
    "laplacian_2d",
    "LinearOp",
    "NonlinearOp",
    "fd_laplacian_symbol_1d",
    "fd_laplacian_symbol_2d",
    # Model
    "MOLModel",
    # Integrators
    "IntegratorType",
    "euler_step",
    "ssprk3_step",
    "rk4_step",
    "be_step",
    "cn_step",
    "bdf2_step",
    "adaptive_integrate",
    # IMEX integrators
    "imex_euler_step",
    "imex_strang_step",
    "imex_ssprk2_step",
    "adaptive_integrate_imex",
    "integrate_imex_fixed_dt",
    # Newton-Krylov
    "newton_krylov_solve",
    # Preconditioners
    "IdentityPreconditioner",
    "BlockJacobiPreconditioner",
    "DiffusionPreconditioner",
    "FFTDiffusionPreconditioner",
    "FFTAdvectionDiffusionPreconditioner",
    "create_fft_preconditioner",
    "create_gray_scott_fft_preconditioner",
    "create_advdiff_fft_preconditioner",
    # dt policy
    "propose_dt",
    "CFLParams",
    "PIDParams",
    "imex_cfl_dt",
    "propose_dt_imex",
    # FFT solvers
    "create_fft_cache",
    "create_fft_cache_1d",
    "create_fft_cache_2d",
    "FFTCache1D",
    "FFTCache2D",
    "laplacian_symbol_1d",
    "laplacian_symbol_2d",
    "solve_helmholtz",
    "solve_helmholtz_1d",
    "solve_helmholtz_2d",
    "apply_diffusion_inverse_fft",
    "apply_diffusion_fft",
    "apply_spectral_filter_state",
    "exponential_filter_1d",
    "exponential_filter_2d",
    # FFT operators
    "FFTLinearOperator",
    "DiffusionOperator",
    "AdvectionDiffusionOperator",
    "exact_cfl_dt",
    # ETD integrators
    "etd1_step",
    "etd2_step",
    "etdrk4_step",
    "etd_integrate",
    "diffusion_only_etd1",
    "fft_imex_euler_step",
    # Batched FFT operations
    "batched_fft_matvec",
    "batched_fft_solve",
    "batched_fft_exp_matvec",
    "stacked_fft_solve_shared_op",
    # JIT-compiled kernels
    "phi1",
    "phi2",
    "phi3",
    "etd1_kernel_1d",
    "etd1_kernel_2d",
    "etd2_kernel_1d",
    "etdrk4_kernel_1d",
    "helmholtz_solve_1d",
    "helmholtz_solve_2d",
    "advdiff_solve_1d",
    "batched_fft_solve_1d",
    "batched_exp_matvec_1d",
    "make_etd1_integrator",
    "benchmark_jit_speedup",
    # Batched multi-field operations
    "batched_etd1_kernel_1d",
    "batched_etd2_kernel_1d",
    "multi_operator_etd1_1d",
    "batched_etd1_kernel_2d",
    "batched_helmholtz_solve_2d",
    "benchmark_batched_scaling",
    "print_batched_scaling_report",
    # GPU benchmarks
    "DeviceInfo",
    "BenchmarkResult",
    "ScalingBenchmark",
    "benchmark_fft_scaling",
    "benchmark_2d_scaling",
    "run_full_benchmark",
    "print_benchmark_report",
    # Non-periodic FFT (Dirichlet/Neumann BCs)
    "NonperiodicBCType",
    "NonperiodicFFTCache",
    "laplacian_symbol_dirichlet",
    "laplacian_symbol_neumann",
    "laplacian_symbol_mixed_dn",
    "create_nonperiodic_fft_cache",
    "solve_poisson_dirichlet",
    "solve_poisson_neumann",
    "solve_helmholtz_dirichlet",
    "solve_helmholtz_neumann",
    "etd1_dirichlet",
    "etd1_neumann",
    "dst_I_fast",
    "idst_I_fast",
    # Higher-order operators (4th-order)
    "d1_fourth_order_1d",
    "d2_fourth_order_1d",
    "d1_ho_1d",
    "d2_ho_1d",
    "laplacian_ho_1d",
    "d1_ho_2d",
    "d2_ho_2d",
    "laplacian_ho_2d",
    "fd_laplacian_symbol_ho_1d",
    "fd_laplacian_symbol_ho_2d",
    "fd_d1_symbol_ho_1d",
    # 6th-order operators
    "d2_sixth_order_1d",
    "fd_laplacian_symbol_6th_1d",
    # Symbol selectors
    "get_laplacian_symbol_1d",
    "get_laplacian_symbol_2d",
    "OperatorOrder",
    # Variable coefficient operators
    "VariableCoeffStats",
    "CirculantApprox",
    "compute_coeff_stats",
    "create_circulant_approx_1d",
    "create_circulant_approx_2d",
    "apply_variable_diffusion_1d",
    "apply_variable_diffusion_2d",
    "solve_helmholtz_circulant_1d",
    "solve_helmholtz_circulant_2d",
    "richardson_iteration_varcoeff_1d",
    "richardson_iteration_varcoeff_2d",
    "assess_circulant_quality",
    "etd1_varcoeff_approx_1d",
    "print_varcoeff_report",
]
